### ISSUE TITLE
Wrong swap sums for jettons with not 9 decimals.

### ISSUE THREAD

**Issue by lapismyt** [lapismyt/ston-fi.py#2]
Swapping jUSDT to [anything]. offer_amount = 0.01, sending 10 jUSDT.

Possible solution:
Check "decimals" field in jetton metadata before swapping.

**Comment by BonifacioCalindoro** [comment]
That should be the solution, you have to add as much zeroes as decimals, so the builder functions in your code should take the big integers as amount_in, instead of taking the float and converting it to_nano (9 decimals)

**Comment by lapismyt** [comment]
Solved
